name: Blog RSS V2
on: push

jobs:
  fetch:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - id: 'update_worksheet_1'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData",
                "args": {
                  "range": "Blog!A2:F8"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - id: 'update_worksheet_2'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData",
                "args": {
                  "range": "Blog!A9:F11"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - id: 'update_worksheet_3'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData",
                "args": {
                  "range": "Blog!A12:F18"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - id: 'update_worksheet_4'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData",
                "args": {
                  "range": "Blog!A19:F25"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - id: 'update_worksheet_5'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData",
                "args": {
                  "range": "Blog!A26:F31"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - id: 'update_worksheet_6'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData",
                "args": {
                  "range": "Blog!A32:F37"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - id: 'update_worksheet_7'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData",
                "args": {
                  "range": "Blog!A38:F43"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - id: 'update_worksheet_8'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData",
                "args": {
                  "range": "Blog!A44:F48"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - id: 'update_worksheet_9'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData",
                "args": {
                  "range": "Blog!A49:F53"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - id: 'update_worksheet_10'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData",
                "args": {
                  "range": "Blog!A54:F58"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - id: 'update_worksheet_11'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData",
                "args": {
                  "range": "Blog!A59:F64"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - id: 'update_worksheet_12'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData",
                "args": {
                  "range": "Blog!A65:F71"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - id: 'update_worksheet_13'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData",
                "args": {
                  "range": "Blog!A72:F76"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - id: 'update_worksheet_14'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData",
                "args": {
                  "range": "Blog!A77:F81"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: dump results
        env:
          RESULTS1: ${{ steps.update_worksheet_1.outputs.results }}
          RESULTS2: ${{ steps.update_worksheet_2.outputs.results }}
          RESULTS3: ${{ steps.update_worksheet_3.outputs.results }}
          RESULTS4: ${{ steps.update_worksheet_4.outputs.results }}
#          RESULTS5: ${{ steps.update_worksheet_5.outputs.results }}
          RESULTS6: ${{ steps.update_worksheet_6.outputs.results }}
          RESULTS7: ${{ steps.update_worksheet_7.outputs.results }}
          RESULTS8: ${{ steps.update_worksheet_8.outputs.results }}
          RESULTS9: ${{ steps.update_worksheet_9.outputs.results }}
#          RESULTS10: ${{ steps.update_worksheet_10.outputs.results }}
#          RESULTS11: ${{ steps.update_worksheet_11.outputs.results }}
#          RESULTS12: ${{ steps.update_worksheet_12.outputs.results }}
#          RESULTS13: ${{ steps.update_worksheet_13.outputs.results }}
#          RESULTS14: ${{ steps.update_worksheet_14.outputs.results }}
        run: |
          echo "$RESULTS1" | jq ".results[0].result.rawData" > blogV2.json
          echo "," >> blogV2.json
          echo "$RESULTS2" | jq ".results[0].result.rawData" >> blogV2.json
          echo "," >> blogV2.json
          echo "$RESULTS3" | jq ".results[0].result.rawData" >> blogV2.json
          echo "," >> blogV2.json
          echo "$RESULTS4" | jq ".results[0].result.rawData" >> blogV2.json
          echo "," >> blogV2.json

          echo "$RESULTS6" | jq ".results[0].result.rawData" >> blogV2.json
          echo "," >> blogV2.json
          echo "$RESULTS7" | jq ".results[0].result.rawData" >> blogV2.json
          echo "," >> blogV2.json
          echo "$RESULTS6" | jq ".results[0].result.rawData" >> blogV2.json
          echo "," >> blogV2.json
          echo "$RESULTS9" | jq ".results[0].result.rawData" >> blogV2.json


      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: Github Actions

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: actions@github.com

          # The name of the branch to use, if different from the one that triggered the workflow.
          # Default: the branch that triggered the run
          branch: gh-pages

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Update blog.json'
