name: Deploy
on:
  workflow_dispatch:

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.0
        with:
          username: 'yzuriha'
          reponame: 'kitanohinako'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
          cname: 'kitanohinako.xyz'
