name: ImageFiles
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Deploy" ]
    types:
      - completed


jobs:
  fetch:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: create Json
        shell: python
        run: |
          # -*- coding: utf-8 -*-
          import os
          import json

          directoryLong = './img/long'
          directorySquare = './img/square'
          dataLong = []
          dataSquare = []
          for filename in os.listdir(directoryLong):
              dataLong.append(filename)

          for filename in os.listdir(directorySquare):
              dataSquare.append(filename)

          jsonString = '{"long":"value1","square": "value2"}'
          jsonObject = json.loads(jsonString)
          jsonObject["long"] = dataLong
          jsonObject["square"] = dataSquare


          directoryForJson = './assets/'
          file_path = os.path.join(directoryForJson, 'imageFiles.json')
          if not os.path.isdir(directoryForJson):
              os.mkdir(directoryForJson)
          with open(file_path, 'w', encoding='utf-8') as outfile:
                      json.dump(jsonObject, outfile, ensure_ascii=False, indent=4)

      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: Github Actions

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: actions@github.com

          # The name of the branch to use, if different from the one that triggered the workflow.
          # Default: the branch that triggered the run
          branch: gh-pages

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Update instagram.json'
