name: RSS
on: push

jobs:
  generate_rss:
    runs-on: macOS-latest
    name: Generate RSS
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: RSS
        id: rss
        uses: katydecorah/instagram-rss-action@v0.2.0
        with:
          yourInstagram: kitanohinako_official
          listOfInstagrams: kitanohinako_official
          pretty: false
      - name: Create Json
        uses: i-valchev/rss-to-json@v1
        with:
          source: https://blog.nogizaka46.com/hinako.kitano/atom.xml
          target: output/feeds.json # An optional parameter to specify the target. Defaults to feeds.json
          sortBy: An optional parameter to sort the feed items by a field. Default is isoDate.
          sortOrder: An optional parameter to specify the order direction. 'desc' or 'asc'. Default is desc.
      - name: Commit file changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet --cached || git commit -m "Update file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}