name: gsheet.action test
on: push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: 1N8wXrd30_sfsKvRoVcoZcpqXDWtsdbyyaF2a-DyjmgM
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData", "args": { "range": "Instagram!A2:F25" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: dump results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq
      - name: Overwrite File
        uses: Radioh/action-content-overwrite@v1.0
        with:
          filePath: "test.txt"
          content: ${{ steps.update_worksheet.outputs.results }}