name: gsheet.action test
on: push

jobs:
  fetch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 2, 4, 6 ]
    steps:
      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData", "args": { "range": "Instagram!A2:F1000" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: dump results
        env:
#            the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq > instagram.json
      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: Author Name

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: mail@example.com
