name: pip
on: push


jobs:
  fetch:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            instaloader
      - name: dump results
#        shell: python
        run: |
          # -*- coding: utf-8 -*-
          instaloader profile kitanohinako_official
      - name: create Json
        shell: python
        run: |
          # -*- coding: utf-8 -*-
          import os
          import json

          directory = './kitanohinako_official'
          data = []
          jsonString = '{"filename":"value1","text":"value2"}'
          jsonObject = json.loads(jsonString)
          for filename in os.listdir(directory):
              if filename.endswith(".jpg") or filename.endswith(".png"):
                  jsonObject["filename"] = filename
                  print(os.path.join(directory, filename))
              elif  filename.endswith(".txt"):
                  with open(os.path.join(directory, filename), encoding='utf-8') as f:
                      lines = f.readlines()
                  jsonObject["text"] = lines
                  print(os.path.join(directory, filename))
              else:
                  continue
              data.append(jsonObject)

          file_path = os.path.join(directory, 'instagram.json')
          with open(file_path, 'w', encoding='utf-8') as outfile:
                        json.dump(data, outfile, ensure_ascii=False, indent=4)

      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: Github Actions

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: actions@github.com

          # The name of the branch to use, if different from the one that triggered the workflow.
          # Default: the branch that triggered the run
          branch: gh-pages

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Update 7gogo.json'
