name: pip
on: push


jobs:
  fetch:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            instaloader
      - name: dump results
        shell: python
        run: |
          # -*- coding: utf-8 -*-
          instaloader profile kitanohinako_official

      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: Github Actions

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: actions@github.com

          # The name of the branch to use, if different from the one that triggered the workflow.
          # Default: the branch that triggered the run
          branch: gh-pages

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Update 7gogo.json'
